### ISSUE TITLE
[Calculator] The wrong month is shown in the End date field

### ISSUE THREAD

**Issue by AnastasiyaLazurenko** [AnastasiyaLazurenko/web.test#13] opened 2024-11-08 18:19 UTC
**Steps to reproduce:**

1. Open the Calculator page
2. Insert the following values into the input fields:

-  Deposit Amount: 1
- Rate of interest: 1
- Investment Term: 1
- Start date: 1/05/2015
- Financial Year: 365

3. Click the Calculate button

**Actual result:** The wrong month is shown in the End date field
**Expected result:** The End date value is formed as the Start date + Investment term

![image](https://github.com/user-attachments/assets/5ae96c68-a501-4d68-b4ec-8bafc8de47a7)

**Comment by varajan** [comment] 2024-11-09 10:50
Cannot reproduce. Maybe it is a duplicate of #10

**Closed as completed** 2024-11-11 13:43 UTC
